spring:
  application:
    name: article-service
  datasource:
    url: jdbc:postgresql://localhost:5432/articledb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:29092  # Critical change for host access
    consumer:
      group-id: article-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.esprit.shared.events"
        spring.json.value.default.type: "com.esprit.shared.events.StockUpdatedEvent"
        session.timeout.ms: 25000  # Increased timeouts
        request.timeout.ms: 30000
    listener:
      missing-topics-fatal: false  # Allows startup without topic existing
      ack-mode: manual_immediate

server:
  port: 8081

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      stock:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka