spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/articledb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
