spring:
  application:
    name: article-service
  datasource:
    url: jdbc:postgresql://localhost:5432/articledb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

resilience4j:
  circuitbreaker:
    instances:
      stock:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2

management:
  endpoints:
    web:
      exposure:
        include: resilience4j.circuitbreakers,health

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


